__all__ = ['voto']
lung = ["1 centimetro",
"2 centimetri",
"3 centimetri",
"4 centimetri",
"5 centimetri",
"6 centimetri",
"7 centimetri",
"8 centimetri",
"9 centimetri",
"10 centimetri",
"11 centimetri",
"12 centimetri",
"13 centimetri",
"14 centimetri",
"15 centimetri",
"16 centimetri",
"17 centimetri",
"18 centimetri",
"19 centimetri",
"20 centimetri",
"21 centimetri",
"22 centimetri",
"23 centimetri",
"24 centimetri",
"25 centimetri",
"26 centimetri",
"27 centimetri",
"28 centimetri",
"29 centimetri",
"30 centimetri",
"69",
"questo non è un pene, riprova più tardi",

                 ]
